# Generated by Django 2.2.7 on 2019-11-05 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twitter_profile', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='twitterprofile',
            name='profile_picture',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
