# Generated by Django 2.2.7 on 2019-11-05 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twitter_profile', '0002_twitterprofile_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='twitterprofile',
            name='profile_picture',
            field=models.ImageField(upload_to='profile/'),
        ),
    ]
