# Generated by Django 2.2.7 on 2019-11-12 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twitter_profile', '0003_auto_20191105_2155'),
    ]

    operations = [
        migrations.AddField(
            model_name='twitterprofile',
            name='biography',
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AddField(
            model_name='twitterprofile',
            name='profile_banner',
            field=models.ImageField(blank=True, upload_to='profile/'),
        ),
        migrations.AddField(
            model_name='twitterprofile',
            name='username',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
