# Generated by Django 2.2.7 on 2019-11-12 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twitter_profile', '0004_auto_20191112_1754'),
    ]

    operations = [
        migrations.AlterField(
            model_name='twitterprofile',
            name='profile_picture',
            field=models.ImageField(blank=True, upload_to='profile/'),
        ),
    ]
